#####
# Documentation
# Redwood: https://render.com/docs/deploy-redwood
# YAML (all config values): https://render.com/docs/yaml-spec
#####

services:
- name: redwood-sample-web
  type: web
  env: static
  buildCommand: yarn install && yarn rw deploy render web
  staticPublishPath: ./web/dist
  envVars:
  - key: NODE_VERSION
    value: 16
  - key: SKIP_INSTALL_DEPS
    value: true
    - key: AUTH0_DOMAIN
    value: dev-qcdzvwp1msiezidl.us.auth0.com
    - key: AUTH0_CLIENT_ID
    value: q7L2EH7FIedsIUNnzw3h9OJCe2NuDNZf
    - key: AUTH0_REDIRECT_URI
    value: https://redwood-sample-web.onrender.com/
    - key: AUTH0_AUDIENCE
    value: https://dev-qcdzvwp1msiezidl.us.auth0.com/api/v2/
  routes:
  - type: rewrite
    source: /.redwood/functions/*
#####
# NOTE: replace destination api url after first deploy to Render
# example:
#   destination: https://myredwoodproject-api.onrender.com/*
#####
    destination: https://*.onrender.com
  - type: rewrite
    source: /*
    destination: /index.html

- name: redwood-sample-api
  type: web
  plan: free
  env: node
  region: oregon
  buildCommand: yarn && yarn rw build api
  startCommand: yarn rw deploy render api
  envVars:
  - key: NODE_VERSION
    value: 17
  - key: DATABASE_URL
    value: file:./data/sqlite.db
